index.html

Related: https://github.com/thoth-station/website-tooling/pull/6

Add a link to AICoE Python package index

---

index.html

Related: https://github.com/thoth-station/website-tooling/pull/7

Adjust link to YouTube channel

---

_j/tf_42679.md

Related: https://github.com/thoth-station/adviser/pull/1211 https://github.com/tensorflow/tensorflow/issues/42679

Add justification document for tf_42679

---

_j/mkl_threads.md

They do not look nice in the listing (not translated to textt).

Remove backticks from justification title

---

_j/tf_25636.md

https://github.com/thoth-station/adviser/pull/1236
https://github.com/tensorflow/tensorflow/issues/25636

Add justification for tf_25636

---

_j/user_stack.md

https://github.com/thoth-station/adviser/pull/1240

Add user-stack justification

---

_j/tf_114_gast.md

https://github.com/thoth-station/adviser/pull/1253
https://github.com/tensorflow/tensorflow/pull/32989
https://github.com/tensorflow/tensorflow/issues/32319

Add justification for tf_114_gast

---

_config.yml
home.markdown

Signed-off-by: Christoph Görn <goern@redhat.com>

added GA code

---

_j/tf_41902.md

https://github.com/thoth-station/adviser/pull/1262
https://github.com/numpy/numpy/pull/15355
https://github.com/tensorflow/tensorflow/commit/79518facb4b857af9d9d5df2da463fdbf7eb0e3e
https://github.com/tensorflow/tensorflow/issues/41902

Add justification for tf_41902

---

_j/tf_41866.md

https://github.com/thoth-station/adviser/pull/1249
https://github.com/tensorflow/tensorflow/pull/41866
https://github.com/tensorflow/tensorflow/issues/40884
https://github.com/tensorflow/tensorflow/issues/35709
https://github.com/tensorflow/tensorflow/pull/40789

Add justification for tf_41866

---

_j/tf_intel.md

See https://github.com/thoth-station/adviser/pull/1313

Add justification for tf_intel

---

_j/tf_cuda_alt.md

See https://github.com/thoth-station/adviser/pull/1313/

Add justification for tf_cuda_alt

---

_j/oom.md

Fixes: https://github.com/thoth-station/thoth-application/issues/559

Extend OOM justification

---

_j/no_paths.md

Signed-off-by: Francesco Murdaca <fmurdaca@redhat.com>

Correct text in no_paths justification

---

index.html

Closes https://github.com/thoth-station/kebechet/issues/576
Redirect to integration docs

Kebechet docs

---

_j/tf_py39.md

Related: https://github.com/thoth-station/adviser/issues/1520
Related: https://github.com/thoth-station/adviser/pull/1528

Add justification for tf-py39 sieve

---

_j/tf_21_h5py.md

Related: https://github.com/thoth-station/adviser/issues/1519
Related: https://github.com/thoth-station/adviser/pull/1529
Related: https://github.com/tensorflow/tensorflow/issues/44467

Add justification for tf_21_h5py

---

_j/si_bandit.md

add doc for bandit justification

---

_j/tf_api.md
_j/tf_no_api.md

Related: https://github.com/thoth-station/adviser/issues/1545
Related: https://github.com/thoth-station/adviser/pull/1560

Add justification for TensorFlow API symbols

---

_j/thamos_timeout.md

Related: https://github.com/thoth-station/thamos/pull/611

Add justification for Thamos timeout

---

_j/tf_38518.md

Related: https://github.com/thoth-station/adviser/pull/1559
Related: https://github.com/tensorflow/tensorflow/issues/38518

Add justification for tf_38518

---

_j/tf_42475.md

Related: https://github.com/thoth-station/adviser/pull/1558
Related: https://github.com/tensorflow/tensorflow/issues/42475

Add justification for slow Keras embedding layer

---

_j/tf_240_avx2.md

Related: https://github.com/thoth-station/adviser/pull/1617

Add justification for tf_240_avx2 sieve

---

_j/no_gpu.md

Related: https://github.com/thoth-station/adviser/pull/1630
Related: https://github.com/thoth-station/thamos/issues/707

Add justification specific to not GPU enabled environments

---

_j/thoth_s2i.md

Related: https://github.com/thoth-station/adviser/pull/1635

Add justification to use Thoth's S2I container images

---

_j/s2i-thoth-f31-py37.md
_j/s2i-thoth-f32-py38.md
_j/s2i-thoth-ubi8-py36.md
_j/s2i-thoth-ubi8-py38.md

These documents are linked from adviser as recommendations are produced.

Add documents describing Thoth S2I

---

index.html

Related: https://github.com/thoth-station/website-tooling/pull/9

Regenerate website based on configuration changes

---

_j/tf_24_np.md

Related: https://github.com/thoth-station/adviser/pull/1694

Add justification for tf_24_np

---

_j/index_package.md

Related: https://github.com/thoth-station/adviser/pull/1720

Add justification for package specific index configuration

---

_j/index_conf.md

Related: https://github.com/thoth-station/adviser/pull/1719

Add justification for strict index configuration

---

_j/selective_prereleases.md

Related: https://github.com/thoth-station/adviser/pull/1718/

Add justification for selective pre-releases

---

_j/rm_user_stack.md

Related: https://github.com/thoth-station/adviser/pull/1726

State removing user's stack if the requirements were adjusted

---

_j/prescription.md

Add prescription information

---

index.html

Thoth API is no longer internal

---

index.html

Related: https://github.com/thoth-station/website-tooling/pull/11

Change primary link to adviser docs

---

_j/constraints.md

Related: https://github.com/thoth-station/core/issues/271
Related: https://github.com/thoth-station/adviser/pull/1826

Add justification for constraints

---

_j/rules.md

Related: https://github.com/thoth-station/thoth-application/issues/1403

Create justification for solver rules

---

_j/eol_env.md

Related: https://github.com/thoth-station/adviser/pull/1896/
Related: https://github.com/thoth-station/thoth-application/issues/1516

Add justification for EOL runtime environment

---

_j/s2i_packages.md

Related: https://github.com/thoth-station/adviser/issues/1948
Related: https://github.com/thoth-station/adviser/pull/1957

Add justification for S2I packages sieve unit

---

_j/rpm.md

Add justification for reporting missing RPM packages

---

_j/install_error.md

Related: https://github.com/thoth-station/adviser/issues/1983

Rename build time error to installation time error

---

_j/trove_py.md

Related: https://github.com/thoth-station/thoth-application/issues/1850

Add justification for classifier based Python interpreter version check

---

_j/trove_inactive.md

Related: https://github.com/thoth-station/thoth-application/issues/1850

Add justification for inactive development status based on classifier

---

_j/trove_cuda.md

Related: https://github.com/thoth-station/thoth-application/issues/1850

Add justification for trove classifier based CUDA version check

---

_j/user_stack.md

Related: https://github.com/thoth-station/adviser/issues/1990
Related: https://github.com/thoth-station/adviser/pull/2027

Notify about unknown dependency graph structure on the backend

---

_j/trove_cuda.md
_j/trove_inactive.md
_j/trove_py.md
_j/trove_unstable.md

Add a link to YouTube video demonstrating Trove classifiers

---

_j/thoth_community.md

Related: https://github.com/thoth-station/prescriptions-refresh-job/issues/41

Add justification for recommendations based on Thoth community

---

_j/lax_version.md

Related: https://github.com/thoth-station/adviser/pull/2204

Provide justification for too lax version

---

_j/eol_env.md

Show how to list environments using thamos on EOL env

---

index.html

https://github.com/thoth-station/help/issues/3
Adds a new tab pointing to the help page
updated index.html

added help tab

---

index.html

n/a
added link to https://fosstodon.org/@thothstation
cc @goern

Added new footer link
